name: webproj
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip>=20.0
  - werkzeug>=1.0
  - flask>=1.0
  - flask-x>=0.1.1
  - flask-cors>=3.0
  - proj-datumgrid-europe=1.4
  - proj-datumgrid-north-america=1.2
  - pyproj>=2.0
